name: Deploy to Bluehost via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build-storybook

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy via SFTP
        run: |
          sshpass -p "$SSH_PASSWORD" sftp -o StrictHostKeyChecking=no angelrob@docs.rezurrector.com <<EOF
            mkdir -p /home2/angelrob/ui.rezurrector.com
            put -r ./storybook-static/* /home2/angelrob/ui.rezurrector.com
            quit
          EOF
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
